# Generated by Django 3.0.8 on 2020-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
