# Generated by Django 3.0.8 on 2020-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='상품명')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='이미지')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('amount', models.IntegerField(verbose_name='수량')),
            ],
        ),
    ]
