# Generated by Django 3.0.8 on 2020-07-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='account',
            field=models.ManyToManyField(to='item.Account'),
        ),
    ]
